// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSPets
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSPets.74ced5aa-4286-436c-b92c-806b823c7e64";
        public const string Name = "VSPets";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
