// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSPets
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSPets.74ced5aa-4286-436c-b92c-806b823c7e64";
        public const string Name = "VS Pets";
        public const string Description = @"Bring your Visual Studio to life with adorable animated pets that walk along your status bar!";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "fun, pets, cat, dog, fox, clippyy";
        public const bool IsPreview = false;
    }
}
