// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSPets
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSPetsString = "e00d6866-a4de-4e76-9769-26f241f5a7ba";
        public static Guid VSPets = new Guid(VSPetsString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int VSPetsMenu = 0x0001;
        public const int VSPetsMenuGroup = 0x0002;
        public const int AddPetCommand = 0x0100;
        public const int AddCatCommand = 0x0110;
        public const int AddDogCommand = 0x0120;
        public const int AddFoxCommand = 0x0130;
        public const int AddClippyCommand = 0x0140;
        public const int AddRubberDuckCommand = 0x0150;
        public const int RemoveAllPetsCommand = 0x0200;
        public const int TogglePetsVisibilityCommand = 0x0300;
    }
}
